name: Heroku deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --tag planninggambler:$(date +%s)
    - uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "planning-gambler"
        heroku_email: "fedir.katushonok@gmail.com"
        usedocker: true
        remote_branch: master
